/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 15-Feb-2018 14:02:24
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */
 
#include "dsplib.h"
#define BL 128;
DATA B[BL] = {
       34,      7,     -3,    -12,    -15,     -9,     -1,     -4,    -28,
      -65,    -92,    -77,      1,    128,    251,    298,    214,     -1,
     -275,   -487,   -524,   -342,     -1,    356,    568,    543,    309,
        0,   -218,   -247,   -120,     18,      1,   -238,   -590,   -811,
     -645,     -2,    940,   1767,   2009,   1386,      2,  -1643,  -2843,
    -3002,  -1936,     -1,   2038,   3333,   3333,   2038,     -1,  -1936,
    -3002,  -2843,  -1643,      2,   1386,   2009,   1767,    940,     -2,
     -645,   -811,   -590,   -238,      1,     18,   -120,   -247,   -218,
        0,    309,    543,    568,    356,     -1,   -342,   -524,   -487,
     -275,     -1,    214,    298,    251,    128,      1,    -77,    -92,
      -65,    -28,     -4,     -1,     -9,    -15,    -12,     -3,      7,
       34
};
