/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 15-Feb-2018 12:30:28
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 128
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 128;
const int16_T B[128] = {
        7,     17,     27,     31,     20,    -11,    -55,    -96,   -112,
      -83,     -6,     97,    187,    219,    167,     39,   -120,   -245,
     -282,   -212,    -68,     86,    183,    188,    121,     38,     -1,
       28,     96,    132,     72,    -96,   -311,   -460,   -438,   -215,
      138,    471,    629,    539,    250,    -88,   -305,   -317,   -170,
      -21,    -32,   -257,   -578,   -747,   -529,    140,   1064,   1824,
     1972,   1266,   -159,  -1791,  -2933,  -3019,  -1896,     69,   2113,
     3403,   3403,   2113,     69,  -1896,  -3019,  -2933,  -1791,   -159,
     1266,   1972,   1824,   1064,    140,   -529,   -747,   -578,   -257,
      -32,    -21,   -170,   -317,   -305,    -88,    250,    539,    629,
      471,    138,   -215,   -438,   -460,   -311,    -96,     72,    132,
       96,     28,     -1,     38,    121,    188,    183,     86,    -68,
     -212,   -282,   -245,   -120,     39,    167,    219,    187,     97,
       -6,    -83,   -112,    -96,    -55,    -11,     20,     31,     27,
       17,      7
};
